#!/usr/bin/env python3
"""Build the final Stage U-B V6 observable table from preserved summaries."""
from __future__ import annotations
import csv,json
from pathlib import Path

HERE=Path(__file__).resolve().parent; ROOT=HERE.parent
co=json.loads((HERE/'coo'/'bands'/'results.json').read_text(encoding='utf-8'))
mn=json.loads((HERE/'mno'/'scf_observables.json').read_text(encoding='utf-8'))
mb=json.loads((HERE/'mno'/'bands'/'results.json').read_text(encoding='utf-8'))
u=json.loads((HERE/'mno'/'authoritative_u_inputs.json').read_text(encoding='utf-8'))
ni_pbe=json.loads((ROOT/'results/stage-ub-v6-observables/run-records/nio-dft.json').read_text(encoding='utf-8'))
ni_lru=json.loads((ROOT/'results/stage-ub-v6-observables/run-records/nio-dft_lru.json').read_text(encoding='utf-8'))

def avg_abs(a:float,b:float)->float:return (abs(a)+abs(b))/2
def moments(run:dict,site0:str,site1:str)->tuple[float,float,float]:
    atoms=run['convergence']['mulliken_atoms']; vals={x['species']:x['moment_muB'] for x in atoms}
    return vals[site0],vals[site1],avg_abs(vals[site0],vals[site1])

ni0=ni_pbe['observables']['correlated_site_moments_muB']; ni1=ni_lru['observables']['correlated_site_moments_muB']
mn_runs=mn['runs']; mn_p0,mn_p1= (x['moment_muB'] for x in mn_runs['PBE']['convergence']['mulliken_atoms'][:2])
mn_l0,mn_l1,mn_lavg=moments(mn_runs['PBE+LR-U central'],'MnLR0','MnLR1')
mn_low0,mn_low1,mn_lowavg=moments(mn_runs['PBE+LR-U low'],'MnLR0','MnLR1')
mn_hi0,mn_hi1,mn_hiavg=moments(mn_runs['PBE+LR-U high'],'MnLR0','MnLR1')
co_p0=co['methods']['PBE']['scf_convergence']['mulliken_atoms'][0]['moment_muB']; co_p1=co['methods']['PBE']['scf_convergence']['mulliken_atoms'][1]['moment_muB']
co_l0=co['methods']['PBE+LR-U']['scf_convergence']['mulliken_atoms'][0]['moment_muB']; co_l1=co['methods']['PBE+LR-U']['scf_convergence']['mulliken_atoms'][1]['moment_muB']

rows=[
 {'material':'NiO','xc':'PBE','u_site0_eV':ni_lru['u_used_eV']['NiLR0'],'u_site1_eV':ni_lru['u_used_eV']['NiLR1'],'u_qualification':'ACCEPTED','pbe_state':'INSULATOR','pbe_gap_mesh_eV':0.97361552,'pbe_local_moment_muB':avg_abs(ni0['NiLR0'],ni0['NiLR1']),'lru_state':'INSULATOR','lru_gap_mesh_eV':3.17656591,'lru_gap_seekpath_eV':3.1771,'lru_min_direct_gap_seekpath_eV':3.9337,'lru_local_moment_muB':avg_abs(ni1['NiLR0'],ni1['NiLR1']),'observable_status':'COMPLETE','u_low_site0_eV':None,'u_low_site1_eV':None,'u_high_site0_eV':None,'u_high_site1_eV':None,'u_low_site0_fraction':None,'u_low_site1_fraction':None,'u_high_site0_fraction':None,'u_high_site1_fraction':None,'gap_low_eV':None,'gap_central_eV':None,'gap_high_eV':None,'moment_low_muB':None,'moment_central_muB':None,'moment_high_muB':None,'u_sensitivity_observable_status':'NOT_RUN','pbe_local_moment_site0_muB':ni0['NiLR0'],'pbe_local_moment_site1_muB':ni0['NiLR1'],'lru_local_moment_site0_muB':ni1['NiLR0'],'lru_local_moment_site1_muB':ni1['NiLR1'],'pbe_route_state':'INSULATOR','lru_route_state':'INSULATOR'},
 {'material':'FeO','xc':'PBE','u_site0_eV':5.638281766243177,'u_site1_eV':5.638315883828983,'u_qualification':'ACCEPTED','pbe_state':'METAL','pbe_gap_mesh_eV':0.0,'pbe_local_moment_muB':3.64505,'lru_state':'INSULATOR','lru_gap_mesh_eV':2.30591557,'lru_gap_seekpath_eV':2.332998519,'lru_min_direct_gap_seekpath_eV':2.480536168,'lru_local_moment_muB':3.9089,'observable_status':'COMPLETE','u_low_site0_eV':None,'u_low_site1_eV':None,'u_high_site0_eV':None,'u_high_site1_eV':None,'u_low_site0_fraction':None,'u_low_site1_fraction':None,'u_high_site0_fraction':None,'u_high_site1_fraction':None,'gap_low_eV':None,'gap_central_eV':None,'gap_high_eV':None,'moment_low_muB':None,'moment_central_muB':None,'moment_high_muB':None,'u_sensitivity_observable_status':'NOT_RUN','pbe_local_moment_site0_muB':3.64505,'pbe_local_moment_site1_muB':-3.64505,'lru_local_moment_site0_muB':3.908901,'lru_local_moment_site1_muB':-3.908899,'pbe_route_state':'METAL','lru_route_state':'INSULATOR'},
 {'material':'CoO','xc':'PBE','u_site0_eV':5.817148502021659,'u_site1_eV':5.815019855497104,'u_qualification':'REVIEW','pbe_state':'METAL','pbe_gap_mesh_eV':0.0,'pbe_local_moment_muB':avg_abs(co_p0,co_p1),'lru_state':'INSULATOR','lru_gap_mesh_eV':2.71482278,'lru_gap_seekpath_eV':co['methods']['PBE+LR-U']['cbm']['indirect_gap_eV'],'lru_min_direct_gap_seekpath_eV':co['methods']['PBE+LR-U']['minimum_direct_gap']['gap_eV'],'lru_local_moment_muB':avg_abs(co_l0,co_l1),'observable_status':'COMPLETE','u_low_site0_eV':None,'u_low_site1_eV':None,'u_high_site0_eV':None,'u_high_site1_eV':None,'u_low_site0_fraction':None,'u_low_site1_fraction':None,'u_high_site0_fraction':None,'u_high_site1_fraction':None,'gap_low_eV':None,'gap_central_eV':None,'gap_high_eV':None,'moment_low_muB':None,'moment_central_muB':None,'moment_high_muB':None,'u_sensitivity_observable_status':'NOT_RUN','pbe_local_moment_site0_muB':co_p0,'pbe_local_moment_site1_muB':co_p1,'lru_local_moment_site0_muB':co_l0,'lru_local_moment_site1_muB':co_l1,'pbe_route_state':'METAL','lru_route_state':co['methods']['PBE+LR-U']['route_classification']},
 {'material':'MnO','xc':'PBE','u_site0_eV':u['central_u_eV']['MnLR0'],'u_site1_eV':u['central_u_eV']['MnLR1'],'u_qualification':'PROTOCOL_REVIEW_REQUIRED','pbe_state':mn_runs['PBE']['scf_mesh']['classification'],'pbe_gap_mesh_eV':mn_runs['PBE']['scf_mesh']['occupation_aware_gap_eV'],'pbe_local_moment_muB':avg_abs(mn_p0,mn_p1),'lru_state':mn_runs['PBE+LR-U central']['scf_mesh']['classification'],'lru_gap_mesh_eV':mn_runs['PBE+LR-U central']['scf_mesh']['occupation_aware_gap_eV'],'lru_gap_seekpath_eV':mb['methods']['PBE+LR-U']['indirect_gap_eV'],'lru_min_direct_gap_seekpath_eV':mb['methods']['PBE+LR-U']['minimum_direct_gap']['gap_eV'],'lru_local_moment_muB':mn_lavg,'observable_status':'COMPLETE','u_low_site0_eV':u['u_interval_by_site']['MnLR0']['lower_eV'],'u_low_site1_eV':u['u_interval_by_site']['MnLR1']['lower_eV'],'u_high_site0_eV':u['u_interval_by_site']['MnLR0']['upper_eV'],'u_high_site1_eV':u['u_interval_by_site']['MnLR1']['upper_eV'],'u_low_site0_fraction':u['u_interval_by_site']['MnLR0']['lower_fraction'],'u_low_site1_fraction':u['u_interval_by_site']['MnLR1']['lower_fraction'],'u_high_site0_fraction':u['u_interval_by_site']['MnLR0']['upper_fraction'],'u_high_site1_fraction':u['u_interval_by_site']['MnLR1']['upper_fraction'],'gap_low_eV':mn_runs['PBE+LR-U low']['scf_mesh']['occupation_aware_gap_eV'],'gap_central_eV':mn_runs['PBE+LR-U central']['scf_mesh']['occupation_aware_gap_eV'],'gap_high_eV':mn_runs['PBE+LR-U high']['scf_mesh']['occupation_aware_gap_eV'],'moment_low_muB':mn_lowavg,'moment_central_muB':mn_lavg,'moment_high_muB':mn_hiavg,'u_sensitivity_observable_status':'QUANTIFIED_SAME_PHASE','pbe_local_moment_site0_muB':mn_p0,'pbe_local_moment_site1_muB':mn_p1,'lru_local_moment_site0_muB':mn_l0,'lru_local_moment_site1_muB':mn_l1,'moment_low_site0_muB':mn_low0,'moment_low_site1_muB':mn_low1,'moment_high_site0_muB':mn_hi0,'moment_high_site1_muB':mn_hi1,'pbe_route_state':mb['methods']['PBE']['route_classification'],'lru_route_state':mb['methods']['PBE+LR-U']['route_classification']},
]
schema={'schema':'stage-ub-v6-observable-validation-table.v1','moment_metric_definition':'single-valued moment columns are mean absolute Mulliken moments over the two correlated AFM sites; per-site signed moments are included as additional fields','gap_scope':'all reported gaps are sampled SCF-mesh or sampled Seekpath-route values, not continuous global BZ proofs','validation_terminal_state':{'NiO':'COMPLETE','FeO':'COMPLETE','CoO':'COMPLETE','MnO':'COMPLETE','PENDING_SIESTA_OBSERVABLE_VALIDATIONS':0,'SIESTA_VALIDATION_PHASE':'CLOSED','READY_FOR_CONSOLIDATION_REVIEW':'YES'},'rows':rows}
jsonpath=HERE/'observable_validation_v6.json'; csvpath=HERE/'observable_validation_v6.csv'
jsonpath.write_text(json.dumps(schema,indent=2,ensure_ascii=False,allow_nan=False)+'\n',encoding='utf-8')
with csvpath.open('w',newline='',encoding='utf-8') as f:
    columns=list(dict.fromkeys(k for row in rows for k in row))
    w=csv.DictWriter(f,fieldnames=columns);w.writeheader();w.writerows(rows)
print(json.dumps({'json':str(jsonpath),'csv':str(csvpath),'rows':len(rows),'terminal':schema['validation_terminal_state']},indent=2))
